# Necessary import

import pandas as pd
import matplotlib.pyplot as plt
import requests
import json

## Part 1. Functions related to historical Coronavirus data of last 30 days
def obtain_historical_data():
    """
    This is a function to obtain historical data using NovelCOVID API.
    API documentation: https://documenter.getpostman.com/view/11144369/Szf6Z9B3?version=latest#513b0f63-b3ae-4427-9e4d-d3f6937789e9
    Official documentation: https://github.com/disease-sh/API
    Authenticaiton: This API does not require a key and it is an open source.

    Parameters (Inputs)
    ----------

    Returns (Output)
    -------
    list
        A list of dictionary with json format containing data of cases, deaths, and recovered for last 30 days in all countries available

    Examples
    --------
    >>> history = obtain_historical_data()
    >>> type(history)
    list
    """
    r = requests.get("https://corona.lmao.ninja/v2/historical?lastdays=30")
    if r.status_code != 200:
        print('API status !=200, failed')
    elif r.status_code == 200:
        print('API status = 200, sucessful')
    historical_data = r.json() # convert the results to json format
    print(json.dumps(historical_data, indent=2, sort_keys=True))
    return(historical_data)

# 1.1 Historical data of cases in each country
def organized_historical_cases(historical_data):
    """
    This is a function of selecting data related to cases from previously generated historical_data
    It includes convert the type of data to DataFrame and organize data.
    The reason of including groupby and sum() is that some of the raw data is listed for provinces available in that country.
    In order to generate the data with whole country, groupby and sum() is in need.

    Parameters (Inputs)
    ----------
    historical_data : list
        The list of data generated by the first function

    Returns (Output)
    -------
    DataFrame
        A DataFrame containing data of cases for last 30 days for all countries available.

    Examples
    --------
    >>> history = obtain_historical_data()
    >>> cases = organized_historical_cases(history)
    >>> type(cases)
    pandas.core.frame.DataFrame
    """
    df = pd.DataFrame(historical_data)
    list_timeline = df['timeline'].values.tolist()
    timeline = pd.DataFrame(list_timeline)
    list_cases = timeline['cases'].values.tolist()
    cases = pd.DataFrame(list_cases)
    cases['country'] = df['country']
    cases_organized = cases.groupby('country').sum()
    return cases_organized

def plot_organized_historical_cases(cases_organized, query_country):
    """
    This is a function for making time series plot showing how the number of cases for last 30 days changes for the specific countru that the user wants to know.

    Parameters (Inputs)
    ----------
    cases_organized : DataFrame
        The DataFrame generated in previous function containing organized data of cases
    query_country : str
        The specific country the user wants to get information about

    Returns (Output)
    -------
    plot
        A line plot showing how the number of cases changes for last 30 days for the specific country users want to know

    Examples
    --------
    >>> history = obtain_historical_data()
    >>> cases = organized_historical_cases(history)
    >>> country = 'China'
    >>> plot_organized_historical_cases(cases, country)
    will return the line plot
    """
    assert isinstance(cases_organized, pd.core.frame.DataFrame), "This function needs DataFrame as input."
    assert isinstance(query_country, str), "The query_country needs to be a string."
    if query_country in cases_organized.index:
        query_country_df = cases_organized.loc[query_country, :]
        query_country_df.transpose().plot(kind='line', subplots=True)
        return plt.show()
    elif query_country not in cases_organized.index:
        print('Query country is not available')

# 1.2 Historical data of deaths in each country
def organized_historical_deaths(historical_data):
    """
    This is a function of selecting data related to deaths from previously generated historical_data
    It includes convert the type of data to DataFrame and organize data.
    The reason of including groupby and sum() is that some of the raw data is listed for provinces available in that country.
    In order to generate the data with whole country, groupby and sum() is in need.

    Parameters (Inputs)
    ----------
    historical_data : list
        The list of data generated by the first function

    Returns (Output)
    -------
    DataFrame
        A DataFrame containing data of deaths for last 30 days for all countries available.

    Examples
    --------
    >>> history = obtain_historical_data()
    >>> deaths = organized_historical_deaths(history)
    >>> type(deaths)
    pandas.core.frame.DataFrame
    """
    df = pd.DataFrame(historical_data)
    list_timeline = df['timeline'].values.tolist()
    timeline = pd.DataFrame(list_timeline)
    list_deaths = timeline['deaths'].values.tolist()
    deaths = pd.DataFrame(list_deaths)
    deaths['country'] = df['country']
    deaths_organized = deaths.groupby('country').sum()
    return deaths_organized

def plot_organized_historical_deaths(deaths_organized, query_country):
    """
    This is a function for making time series plot showing how the number of deaths for last 30 days changes for the specific countru that the user wants to know.

    Parameters (Inputs)
    ----------
    deaths_organized : DataFrame
        The DataFrame generated in previous function containing organized data of deaths
    query_country : str
        The specific country the user wants to get information about

    Returns (Output)
    -------
    plot
        A line plot showing how the number of deaths changes for last 30 days for the specific country users want to know

    Examples
    --------
    >>> history = obtain_historical_data()
    >>> deaths = organized_historical_deaths(history)
    >>> country = 'China'
    >>> plot_organized_historical_deaths(deaths, country)
    will return the line plot
    """
    assert isinstance(deaths_organized, pd.core.frame.DataFrame), "This function needs DataFrame as input."
    assert isinstance(query_country, str), "The query_country needs to be a string."
    if query_country in deaths_organized.index:
        query_country_df = deaths_organized.loc[query_country, :]
        query_country_df.transpose().plot(kind='line', subplots=True)
        return plt.show()
    elif query_country not in deaths_organized.index:
        print('Query country is not available')

# 1.3 Historical data of recovered in each country
def organized_historical_recovered(historical_data):
    """
    This is a function of selecting data related to recovered from previously generated historical_data
    It includes convert the type of data to DataFrame and organize data.
    The reason of including groupby and sum() is that some of the raw data is listed for provinces available in that country.
    In order to generate the data with whole country, groupby and sum() is in need.

    Parameters (Inputs)
    ----------
    historical_data : list
        The list of data generated by the first function

    Returns (Output)
    -------
    DataFrame
        A DataFrame containing data of recovered for last 30 days for all countries available.

    Examples
    --------
    >>> history = obtain_historical_data()
    >>> recovered = organized_historical_recovered(history)
    >>> type(recovered)
    pandas.core.frame.DataFrame
    """
    df = pd.DataFrame(historical_data)
    list_timeline = df['timeline'].values.tolist()
    timeline = pd.DataFrame(list_timeline)
    list_recovered = timeline['recovered'].values.tolist()
    recovered = pd.DataFrame(list_recovered)
    recovered['country'] = df['country']
    recovered_organized = recovered.groupby('country').sum()
    return recovered_organized

def plot_organized_historical_recovered(recovered_organized, query_country):
    """
    This is a function for making time series plot showing how the number of recovered for last 30 days changes for the specific countru that the user wants to know.

    Parameters (Inputs)
    ----------
    deaths_organized : DataFrame
        The DataFrame generated in previous function containing organized data of recovered
    query_country : str
        The specific country the user wants to get information about

    Returns (Output)
    -------
    plot
        A line plot showing how the number of recovered changes for last 30 days for the specific country users want to know

    Examples
    --------
    >>> history = obtain_historical_data()
    >>> recovered = organized_historical_recovered(history)
    >>> country = 'China'
    >>> plot_organized_historical_recovered(recovered, country)
    will return the line plot
    """
    assert isinstance(recovered_organized, pd.core.frame.DataFrame), "This function needs DataFrame as input."
    assert isinstance(query_country, str), "The query_country needs to be a string."
    if query_country in recovered_organized.index:
        query_country_df = recovered_organized.loc[query_country, :]
        query_country_df.transpose().plot(kind='line', subplots=True)
        return plt.show()
    elif query_country not in recovered_organized.index:
        print('Query country is not available')

## Part 2. Functions for acquiring data of different scope
# 2.1 Acquiring data at the scope of global level
def obtain_global_data():
    """
    This is a function used to generate data at global level, using another endpoint of NovelCOVID API.
    API documentation: https://documenter.getpostman.com/view/11144369/Szf6Z9B3?version=latest#513b0f63-b3ae-4427-9e4d-d3f6937789e9
    Official documentation: https://github.com/disease-sh/API
    Authenticaiton: This API does not require a key and it is an open source.

    Parameters (Inputs)
    ----------

    Returns (Output)
    -------
    DataFrame
        A DataFrame object containing yesterday's data at global level

    Examples
    --------
    >>> global_yesterday = obtain_global_data()
    >>> type(global_yesterday)
    pandas.core.frame.DataFrame
    """
    r = requests.get("https://corona.lmao.ninja/v2/all?yesterday")
    if r.status_code != 200:
        print('API status !=200, failed')
    elif r.status_code == 200:
        print('API status = 200, sucessful')
    global_data = r.json()
    print(json.dumps(global_data, indent=2, sort_keys=True))
    df = pd.Series(global_data).to_frame('yesterday data')
    return(df)

# 2.2 Acquiring data at the scope of continents, and following with bar plot provided
def obtain_continent_data():
    """
    This is a function used to generate data at global level, using another endpoint of NovelCOVID API.
    API documentation: https://documenter.getpostman.com/view/11144369/Szf6Z9B3?version=latest#513b0f63-b3ae-4427-9e4d-d3f6937789e9
    Official documentation: https://github.com/disease-sh/API
    Authenticaiton: This API does not require a key and it is an open source.

    Parameters (Inputs)
    ----------

    Returns (Output)
    -------
    DataFrame
        A DataFrame object containing yesterday's data of each continents

    Examples
    --------
    >>> continent_yesterday = obtain_continent_data()
    >>> type(continent_yesterday)
    pandas.core.frame.DataFrame
    """
    r = requests.get("https://corona.lmao.ninja/v2/continents?yesterday=true&sort")
    if r.status_code != 200:
        print('API status !=200, failed')
    elif r.status_code == 200:
        print('API status = 200, sucessful')
    continent_data = r.json()
    continent_df = pd.DataFrame(continent_data)
    return(continent_df)

def continent_bar_plot(continent_df,i):
    """
    This is a function used to plot bar graph of any available column containing data of each continent.

    Parameters (Inputs)
    ----------
    continent_df : DataFrame
        The DataFrame generated in previous function containing data of each continent
    i : str
        The specific column the user wants to get bar graph about.
        Shoube belongs to the list ['cases','todayCases','deaths','todayDeaths','recovered','todayRecovered','active',
                                    'critical','casesPerOneMillion','deathsPerOneMillion','tests','testsPerOneMillion',
                                    'population','activePerOneMillion','recoveredPerOneMillion','criticalPerOneMillion']

    Returns (Output)
    -------
    plot
        A bar plot showing the information of each continent

    Examples
    --------
    >>> continent_yesterday = obtain_continent_data()
    >>> i = 'cases'
    >>> continent_bar_plot(continent_yesterday, i)
    will return the bar plot
    """
    available_list = ['cases','todayCases','deaths','todayDeaths','recovered','todayRecovered','active','critical',
                      'casesPerOneMillion','deathsPerOneMillion','tests','testsPerOneMillion','population',
                      'activePerOneMillion','recoveredPerOneMillion','criticalPerOneMillion']
    assert i in available_list, "input is not in available list, please check the table provided by obtain_continent_data()"
    fig = plt.figure()
    ax = fig.add_axes([0,0,1,1])
    continent = continent_df['continent']
    if i in available_list:
        y_axis = continent_df[i]
        ax.bar(continent,y_axis)
        bar_plot = plt.show()
    return bar_plot


